/*
* generated by Xtext
*/
package org.xtext.example.mydsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RDslStandaloneSetup extends RDslStandaloneSetupGenerated{

	public static void doSetup() {
		new RDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

